openapi: 3.0.1
info:
  description: REST API for creating and retrieving ip records
  version: '1.0'
  title: Intel 471 IP service
tags:
  - name: IpRecords
    description: Endpoints for creating and retrieving ip records
paths:
  /ip-records/:
    get:
      tags:
        - IpRecords
      operationId: getIpRecordByValue
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IpRecord'
    post:
      tags:
        - IpRecords
      operationId: createIpRecord
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIpRecordDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpRecord'
        '400':
          description: Bad Request
components:
  schemas:
    IpRecord:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
        value:
          type: string
        firstSeen:
          type: string
          pattern: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}
        totalCount:
          type: integer
    CreateIpRecordDto:
      type: object
      properties:
        type:
          type: string
          nullable: true
        value:
          type: string
          nullable: false
        firstSeen:
          type: string
          pattern: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}
        totalCount:
          type: integer
          minimum: 0
          maximum: 100